authors/models.py
from db import db
from sqlalchemy.orm import relationship


class Authors(db.Model):
    id_a = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    nationality_id = db.Column(db.Integer, db.ForeignKey('nationalities.id_n'), nullable=False)
    nationality = relationship("Nationalities", lazy="select", backref=db.backref('Nationalities', lazy='joined'))
    number_of_songs = db.Column(db.Integer, nullable=False)
    number_of_albums = db.Column(db.Integer, nullable=False)
    url_photo = db.Column(db.VARCHAR(2083), nullable=True)
    short_description = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime, nullable=True)
    updated_at = db.Column(db.DateTime, nullable=True)

authors/__init__.py
from flask import Blueprint

bp = Blueprint('authors',
               __name__,
               template_folder="templates",
               url_prefix="/authors")

from authors import views

authors/views.py
import datetime

from flask import (render_template, request, url_for, redirect, flash)
from authors import bp
from authors.models import Authors
from nationalities.models import Nationalities
from db import db


@bp.route("/")
def index_view():
    authors = db.paginate(db.select(Authors).order_by(Authors.id_a), per_page=3)

    return render_template("authors/index.html", authors=authors, title="SQLAlchemyORM - Authors", name=authors,
                           url='authors.index_view')


@bp.route("/edit/<id>", methods=["POST", "GET"])
def update_view(id):
    if not id:
        return redirect(url_for("authors.index_view"))
    try:
        author = db.session.execute(db.select(Authors).filter_by(id_a=id)).first()
        nationalities = db.session.execute(db.select(Nationalities)).unique().all()

    except Exception:
        flash("This author does not exist", "error")
        return redirect(url_for("authors.index_view"))

    if request.method == "POST":
        print(request.form["name"])
        author[0].name = request.form["name"]
        author[0].nationality_id = request.form["nationality"]
        author[0].number_of_songs = request.form["number_of_songs"]
        author[0].number_of_albums = request.form["number_of_albums"]
        author[0].url_photo = request.form["url_photo"]
        author[0].updated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        author[0].verified = True
        db.session.add(author[0])
        db.session.commit()

        flash("Author was updated", "success")
        return redirect(url_for("authors.index_view"))

    return render_template("authors/update.html", author=author, nationalities=nationalities)


@bp.route("/inspect/<id>", methods=["POST", "GET"])
def inspect_view(id):
    try:
        author = db.session.execute(db.select(Authors).filter_by(id_a=id)).first()
        nationalities = db.session.execute(db.select(Nationalities)).unique().all()
    except Exception:
        flash("This author does not exist", "error")
        return redirect(url_for("authors.index_view"))

    return render_template("authors/inspect.html", author=author, nationalities=nationalities)


@bp.route("/add", methods=["POST", "GET"])
def add_view():
    if request.method == "POST":
        author_name = request.form["name"]
        author_nationality = request.form["nationality"]
        author_number_of_songs = request.form["number_of_songs"]
        author_number_of_albums = request.form["number_of_albums"]
        author_url_photo = request.form["url_photo"]
        author_short_description = request.form["short_description"]
        author_created_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        author_updated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        if author_url_photo == "NULL":
            author = Authors(name=author_name, nationality_id=author_nationality, number_of_songs=author_number_of_songs,
                         number_of_albums=author_number_of_albums,
                         short_description=author_short_description, created_at=author_created_at,
                         updated_at=author_updated_at)
        else:
            author = Authors(name=author_name, nationality_id=author_nationality,
                             number_of_songs=author_number_of_songs,
                             number_of_albums=author_number_of_albums, url_photo=author_url_photo,
                             short_description=author_short_description, created_at=author_created_at,
                             updated_at=author_updated_at)

        db.session.add(author)
        db.session.commit()

        flash("Author was successfully added to database!", "success")
        return redirect(url_for("authors.index_view"))

    else:
        nationalities = db.session.execute(db.select(Nationalities)).unique().all()
        return render_template("authors/add.html", nationalites=nationalities)


@bp.route("/delete/<id>", methods=["POST", "DELETE"])
def delete_record(id):
    if not id:
        return redirect(url_for("authors.index_view"))
    try:
        author = db.session.execute(db.select(Authors).filter_by(id_a=id)).first()
    except Exception:
        flash("This author does not exist", "error")
        return redirect(url_for("authors.index_view"))

    if request.method == "POST":
        db.session.delete(author[0])
        print(author[0].id_a)
        db.session.commit()
        flash('Author was successfully deleted from database', 'success')
        return redirect(url_for("authors.index_view"))

templates/authors/add.html
{% extends "menu.html" %}

{% block content %}

    <div class="card" style="margin-top: 20px">
        <div class="card-header text-center">
            Add new Author
        </div>
        <div class="card-body">
            <form method="post">
                <div class="form-group">
                    <label for="titleOfsong">Author's name</label>
                    <input name="name" id="name" type="text" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="genreSelect">Author's nationality</label>
                    <select class="form-control" name="nationality" id="nationality">
                        {% for nationality in nationalites %}
                            <option value="{{ nationality[0].id_n }}">{{ nationality[0].nationality }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="numberOfSongs">Number Of Songs</label>
                    <input name="number_of_songs" id="number_of_songs" type="number" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="releaseYear">Number of Albums</label>
                    <input name="number_of_albums" id="number_of_albums" type="number" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="photoURL">Photo URL</label>
                    <input name="url_photo" id="url_photo" type="url" class="form-control">
                </div>
                <div class="form-group">
                    <label for="shortDescription">Short Description</label>
                    <textarea name="short_description" id="short_description" class="form-control"></textarea>
                </div>
                <button type="submit" class="btn btn-primary" style="margin-top: 10px">Add Author</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/authors/index.html
{% extends "paging.html" %}

{% block content %}
    <div class="card-group" style="margin-top: 20px">
        {% for author in authors.items %}
            <div class="card text-center" style="padding-left: 2px">
                <img src="{{ author.url_photo }}" class="card-img-top" alt="Photo of {{ author.name }}"
                     style="width: 400px;height: 350px!important;">
                <div class="card-body">
                    <h5 class="card-title"><a href="{{ url_for("authors.inspect_view", id=author.id_a) }}"
                                              class="link-info author-name">{{ author.name }}</a></h5>
                    <p class="card-text">{{ author.short_description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Nationality: {{ author.nationality.nationality }}</li>
                    <li class="list-group-item">Number of songs: {{ author.number_of_songs }} </li>
                    <li class="list-group-item">Number of albums: {{ author.number_of_albums }}</li>
                </ul>
                <div class="card-footer">
                    <a href="{{ url_for("authors.update_view", id=author.id_a) }}" class="btn btn-light">Update</a>
                    <a href="#" class="btn btn-danger"
                       onclick="$('#authors-delete--{{ author.id_a }}').submit()">Delete</a>
                    <form action="{{ url_for("authors.delete_record", id=author.id_a) }}" method="POST"
                          id="album-delete--{{ author.id_a }}">
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>

    <p class="text-left mt-3">
        <a href="{{ url_for("authors.add_view") }}" class="btn btn-primary">Add author</a>
    </p>
{% endblock %}

templates/authors/inspect.html
{% extends "menu.html" %}

{% block content %}

    <div class="card" style="width: 18rem;margin-top: 20px;margin-left: auto;margin-right: auto">
        <img src="{{ author[0].url_photo }}" class="card-img-top" alt="Photo of {{ author[0].name }}">
        <div class="card-body">
            <h5 class="card-title">{{ author[0].name }}</h5>
            <p class="card-text">{{ author[0].short_description }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Nationality: {{ author[0].nationality.nationality }}</li>
            <li class="list-group-item">Number of songs: {{ author[0].number_of_songs }} </li>
            <li class="list-group-item">Number of albums: {{ author[0].number_of_albums }}</li>
            <li class="list-group-item">Songs:
                <ul>
                    {% for song in author[0].songs %}
                        <li><a href="{{ url_for('songs.inspect_view', id=song.id_s) }}">{{ song.name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    </div>

{% endblock %}

templates/authors/update.html
{% extends "menu.html" %}

{% block content %}

    <div class="card">
        <div class="card-header text-center" style="margin-top: 20px">
            Editing <span style="font-weight: bold">{{ author[0].name }}</span>
        </div>
        <div class="card-body">
            <form method="post">
                <div class="form-group">
                    <label for="titleOfAlbum">Author's name</label>
                    <input name="name" id="name" type="text" class="form-control" value="{{ author[0].name }}" required>
                </div>
                <div class="form-group">
                    <label for="authorSelect">Author's nationality</label>
                    <select class="form-control" name="nationality" id="nationality">
                        <option value="{{ author[0].nationality_id }}">{{ author[0].nationality.nationality }}</option>
                        {% for nationality in nationalities %}
                            <option value="{{ nationality[0].id_n }}">{{ nationality[0].nationality }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="numberOfSongs">Number Of Songs</label>
                    <input name="number_of_songs" id="number_of_songs" type="number" class="form-control"
                           value="{{ author[0].number_of_songs }}" required>
                </div>
                <div class="form-group">
                    <label for="lengthInSec">Number of Albums</label>
                    <input name="number_of_albums" id="number_of_albums" type="number" class="form-control"
                           value="{{ author[0].number_of_albums }}" required>
                </div>
                <div class="form-group">
                    <label for="coverURL">Photo URL</label>
                    <input name="url_photo" id="url_photo" type="url" class="form-control"
                           value="{{ author[0].url_photo }}">
                </div>
                <button type="submit" class="btn btn-primary" style="margin-top: 10px">Update</button>
            </form>
        </div>
    </div>

{% endblock %}