albums/models.py
from db import db
from authors.models import Authors


class Albums(db.Model):
    id_a = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64), nullable=False)
    release_year = db.Column(db.Integer, nullable=False)
    number_of_songs = db.Column(db.Integer, nullable=False)
    length_sec = db.Column(db.Integer, nullable=False)
    author_id = db.Column(db.Integer, db.ForeignKey(Authors.id_a), nullable=True)
    author = db.relationship('Authors', lazy='select', backref=db.backref('Authors', lazy='joined'))
    url_cover = db.Column(db.VARCHAR(2083), nullable=True)
    created_at = db.Column(db.DateTime, nullable=True)
    updated_at = db.Column(db.DateTime, nullable=True)

albums/__init__.py
from flask import Blueprint

bp = Blueprint('albums',
               __name__,
               template_folder="templates",
               url_prefix="/albums")

from albums import views

albums/views.py
import datetime

from flask import (render_template, request, url_for, redirect, flash)
from albums import bp
from db import db
from albums.models import Albums
from albums.models import Authors


@bp.route("/")
def index_view():
    albums = db.paginate(db.select(Albums).order_by(Albums.id_a), per_page=3)

    return render_template("albums/index.html", albums=albums, title="SQLAlchemyORM - Albums", name=albums,
                           url='albums.index_view')


@bp.route("/inspect/<id>", methods=["POST", "GET"])
def inspect_view(id):
    try:
        album = db.session.execute(db.select(Albums).filter_by(id_a=id)).first()
    except Exception:
        flash("This author does not exist", "error")
        return redirect(url_for("albums.index_view"))

    return render_template("albums/inspect.html", album=album)


@bp.route("/edit/<id>", methods=["POST", "GET"])
def update_view(id):
    if not id:
        return redirect(url_for("albums.index_view"))
    try:
        album = db.session.execute(db.select(Albums).filter_by(id_a=id)).first()
        authors = db.session.execute(db.select(Authors)).unique().all()
    except Exception:
        flash("This album does not exist", "error")
        return redirect(url_for("albums.index_view"))

    if request.method == "POST":
        album[0].title = request.form["title"]
        album[0].release_year = request.form["release_year"]
        album[0].number_of_songs = request.form["number_of_songs"]
        album[0].length_sec = request.form["length_sec"]
        album[0].author_id = request.form["author"]
        album[0].url_cover = request.form["url_cover"]
        album[0].updated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        album[0].verified = True
        db.session.add(album[0])
        db.session.commit()

        flash("Album updated", "success")
        return redirect(url_for("albums.index_view"))

    return render_template("albums/update.html", album=album, authors=authors)


@bp.route("/delete/<id>", methods=["POST", "DELETE"])
def delete_record(id):
    if not id:
        return redirect(url_for("albums.index_view"))
    try:
        album = db.session.execute(db.select(Albums).filter_by(id_a=id)).first()
    except Exception:
        flash("This album does not exist", "error")
        return redirect(url_for("albums.index_view"))

    if request.method == "POST":
        db.session.delete(album[0])
        db.session.commit()
        flash('Album was successfully deleted from database', 'success')
        return redirect(url_for("albums.index_view"))


@bp.route("/add", methods=["POST", "GET"])
def add_view():
    if request.method == "POST":
        album_title = request.form["title"]
        album_release_year = request.form["release_year"]
        album_number_of_songs = request.form["number_of_songs"]
        album_length_sec = request.form["length_sec"]
        album_author_id = request.form["author"]
        album_url_cover = request.form["url_cover"]
        album_created_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        album_updated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        album = Albums(title=album_title, release_year=album_release_year, number_of_songs=album_number_of_songs,
                       length_sec=album_length_sec, author_id=album_author_id, url_cover=album_url_cover, created_at=album_created_at,
                       updated_at=album_updated_at)

        db.session.add(album)
        db.session.commit()

        flash("Album was successfully added to database!", "success")
        return redirect(url_for("albums.index_view"))

    else:
        authors = db.session.execute(db.select(Authors)).unique().all()
        return render_template("albums/add.html", authors=authors)

templates/albums/add.html
{% extends "menu.html" %}

{% block content %}

    <div class="card" style="margin-top: 20px">
        <div class="card-header text-center">
            Add new Album
        </div>
        <div class="card-body">
            <form method="post">
                <div class="form-group">
                    <label for="titleOfsong">Title of the album</label>
                    <input name="title" id="title" type="text" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="lengthOfSong">Release year</label>
                    <input type="number" name="release_year" id="release_year" class="form-control">
                </div>
                <div class="form-group">
                    <label for="numberOfSongs">Number Of Songs</label>
                    <input name="number_of_songs" id="number_of_songs" type="number" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="releaseYear">Length in sec</label>
                    <input name="length_sec" id="length_sec" type="number" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="coverURL">Cover URL</label>
                    <input name="url_cover" id="url_cover" type="url" class="form-control">
                </div>
                <div class="form-group">
                    <label for="genreSelect">Author</label>
                    <select class="form-control" name="author" id="author">
                        {% for author in authors %}
                            <option value="{{ author[0].id_a }}">{{ author[0].name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary" style="margin-top: 10px">Add album</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/albums/index.html
{% extends "paging.html" %}

{% block content %}
    <div class="card-group" style="margin-top: 20px">
        {% for album in albums.items %}
            <div class="card text-center" style="padding-left: 2px">
                <img src="{{ album.url_cover }}" class="card-img-top" alt="Photo of {{ album.title }}"
                     style="width: 400px;height: 350px!important;">
                <div class="card-body">
                    <h5 class="card-title">{{ album.title }}</h5>
                    <p class="card-text">{{ album.short_description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Release year: {{ album.release_year }}</li>
                    <li class="list-group-item">Number of songs: {{ album.number_of_songs }}</li>
                    <li class="list-group-item">Length in sec: {{ album.length_sec }}</li>
                    <li class="list-group-item">Author: <a href="{{ url_for("authors.inspect_view", id=album.author.id_a) }}" style="text-decoration: none; color: unset">{{ album.author.name }}</a></li>
                </ul>
                <div class="card-footer">
                    <a href="{{ url_for("albums.update_view", id=album.id_a) }}" class="btn btn-light">Update</a>
                    <a href="#" class="btn btn-danger"
                       onclick="$('#album-delete--{{ album.id_a }}').submit()">Delete</a>
                    <form action="{{ url_for("albums.delete_record", id=album.id_a) }}" method="POST"
                          id="album-delete--{{ album.id_a }}">
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>
    <p class="text-left mt-3">
        <a href="{{ url_for("albums.add_view") }}" class="btn btn-primary">Add album</a>
    </p>
{% endblock %}

templates/albums/inspect.html
{% extends "menu.html" %}

{% block content %}

    <div class="card" style="width: 18rem;margin-top: 20px;margin-left: auto;margin-right: auto">
        <img src="{{ album[0].url_cover }}" class="card-img-top" alt="Photo of {{ album[0].title }}">
        <div class="card-body">
            <h5 class="card-title">{{ album[0].title }}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Release year: {{ album[0].release_year }}</li>
            <li class="list-group-item">Number of songs: {{ album[0].number_of_songs }}</li>
            <li class="list-group-item">Length in sec: {{ album[0].length_sec }}</li>
            <li class="list-group-item">Author: {{ album[0].author.name }}</li>
        </ul>
    </div>

{% endblock %}

templates/albums/update.html
{% extends "menu.html" %}

{% block content %}

    <div class="card" style="margin-top: 20px">
        <div class="card-header text-center">
            Editing <span style="font-weight: bold">{{ album[0].title }}</span>
        </div>
        <div class="card-body">
            <form method="post">
                <div class="form-group">
                    <label for="titleOfAlbum">Title of album</label>
                    <input name="title" id="title" type="text" class="form-control" value="{{ album[0].title }}"
                           required>
                </div>
                <div class="form-group">
                    <label for="releaseYear">Release Year</label>
                    <input name="release_year" id="release_year" type="number" class="form-control"
                           value="{{ album[0].release_year }}" required>
                </div>
                <div class="form-group">
                    <label for="numberOfSongs">Number Of Songs</label>
                    <input name="number_of_songs" id="number_of_songs" type="number" class="form-control"
                           value="{{ album[0].number_of_songs }}" required>
                </div>
                <div class="form-group">
                    <label for="lengthInSec">Length in Seconds</label>
                    <input name="length_sec" id="length_sec" type="number" class="form-control"
                           value="{{ album[0].length_sec }}" required>
                </div>
                <div class="form-group">
                    <label for="authorSelect">Change author</label>
                    <select class="form-control" name="author" id="author">
                        <option value="{{ album[0].author_id }}">{{ album[0].author.name }}</option>
                        {% for author in authors %}
                            <!-- If for not showing current id two times -->
                            {% if author[0].id_a != album[0].author_id %}
                                <option value="{{ author[0].id_a }}">{{ author[0].name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="lengthInSec">Length in Seconds</label>
                    <input name="length_sec" id="length_sec" type="number" class="form-control"
                           value="{{ album[0].length_sec }}" required>
                </div>
                <div class="form-group">
                    <label for="coverURL">Cover URL</label>
                    <input name="url_cover" id="url_cover" type="url" class="form-control" value="{{ album[0].url_cover }}">
                </div>
                <button type="submit" class="btn btn-primary" style="margin-top: 10px">Update</button>
            </form>
        </div>
    </div>

{% endblock %}