songs/models.py
from db import db
from albums.models import Albums
from authors.models import Authors
from authors_songs.tables import authors_songs


class Songs(db.Model):
    id_s = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)
    genre_id = db.Column(db.Integer, db.ForeignKey('genres.id_g'), nullable=False)
    genre = db.relationship("Genres", lazy="select", backref=db.backref('Genres', lazy='joined'))
    length = db.Column(db.Integer, nullable=False)
    number_of_plays = db.Column(db.Integer, nullable=False)
    album_id = db.Column(db.Integer, db.ForeignKey(Albums.id_a), nullable=True)
    album = db.relationship('Albums', lazy='select', backref=db.backref('Albums', lazy='joined'))
    release_year = db.Column(db.Integer, nullable=True)
    url_cover = db.Column(db.VARCHAR(2083), nullable=True)
    created_at = db.Column(db.DateTime, nullable=True)
    updated_at = db.Column(db.DateTime, nullable=True)
    authors = db.relationship('Authors', secondary='authors_songs', backref=db.backref('songs', lazy=True))

    def __repr__(self):
        return f'<Song {self.id_s} {self.name}>'

songs/__init__.py
from flask import Blueprint

bp = Blueprint('songs',
               __name__,
               template_folder="templates",
               url_prefix="/songs")

from songs import views

songs/views.py
import datetime

from flask import (render_template, request, url_for, redirect, flash)

from authors.models import Authors
from songs import bp

from songs.models import Songs
from genres.models import Genres
from albums.models import Albums
from db import db


@bp.route("/")
def index_view():

    songs = Songs.query.all()
    return render_template("songs/index.html",
                           songs=songs, title="SQLAlchemyORM - Songs",
                           name=songs, url='songs.index_view')


@bp.route("/edit/<id>", methods=["POST", "GET"])
def update_view(id):
    if not id:
        return redirect(url_for("songs.index_view"))
    try:
        song = Songs.query.get(id)
        genres = Genres.query.all()
        albums = Albums.query.all()
    except Exception:
        flash("This song does not exist", "error")
        return redirect(url_for("songs.index_view"))

    if request.method == "POST":
        song.name = request.form["name"]
        song.genre_id = request.form["genre"]
        song.length = request.form["length"]
        song.number_of_plays = request.form["number_of_plays"]
        if song.album_id is "None":
            print(song.album_id)
            song.album_id = None
        else:
            song.album_id = request.form["album"]
        song.release_year = request.form["release_year"]
        song.url_cover = request.form["url_cover"]
        song.updated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        song.verified = True
        db.session.add(song)
        db.session.commit()

        flash("Song updated", "success")
        return redirect(url_for("songs.index_view"))

    return render_template("songs/update.html", song=song, albums=albums, genres=genres)


@bp.route("/inspect/<id>", methods=["POST", "GET"])
def inspect_view(id):
    try:
        song = db.session.execute(db.select(Songs).filter_by(id_s=id)).first()
    except Exception:
        flash("This song does not exist", "error")
        return redirect(url_for("songs.index_view"))

    return render_template("songs/inspect.html", song=song)


@bp.route("/add", methods=["POST", "GET"])
def add_view():
    if request.method == "POST":
        song_name = request.form["name"]
        song_genre_id = request.form["genre"]
        song_length = request.form["length"]
        song_number_plays = request.form["number_of_plays"]
        song_album_id = request.form["album"]
        song_release_year = request.form["release_year"]
        song_url_cover = request.form["url_cover"]
        song_created_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        song_updated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        if song_album_id == "NULL" or song_url_cover == "NULL":
            song = Songs(name=song_name, genre_id=song_genre_id, length=song_length, number_of_plays=song_number_plays, release_year=song_release_year, created_at=song_created_at ,updated_at=song_updated_at)
        else:
            song = Songs(name=song_name, genre_id=song_genre_id, length=song_length, urL_cover = song_url_cover,number_of_plays=song_number_plays, album_id=song_album_id,release_year=song_release_year, created_at=song_created_at ,updated_at=song_updated_at)

        db.session.add(song)

        authors = request.form.getlist("author")
        print(authors)
        for author_id in authors:
            author = Authors.query.filter_by(id_a=author_id).first()
            if author:
                song.authors.append(author)

        db.session.commit()

        flash("Song was successfully added to database!", "success")
        return redirect(url_for("songs.index_view"))

    else:
        genres = Genres.query.all()
        albums = Albums.query.all()
        authors = Authors.query.all()
        return render_template("songs/add.html", albums=albums, genres=genres, authors=authors)


@bp.route("/delete/<id>", methods=["POST", "DELETE"])
def delete_record(id):
    if not id:
        return redirect(url_for("songs.index_view"))
    try:
        song = Songs.query.get(id)
    except Exception:
        flash("This song does not exist", "error")
        return redirect(url_for("songs.index_view"))

    if request.method == "POST":
        db.session.delete(song)
        print(song.id_s)
        db.session.commit()
        flash("Song was successfully deleted from database", "success")
        return redirect(url_for("songs.index_view"))

templates/songs/add.html
{% extends "menu.html" %}

{% block content %}

    <div class="card" style="margin-top: 20px">
        <div class="card-header text-center">
            Add song
        </div>
        <div class="card-body">
            <form method="post">
                <div class="form-group">
                    <label for="titleOfsong">Name of the song</label>
                    <input name="name" id="name" type="text" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="genreSelect">Genre</label>
                    <select class="form-control" name="genre" id="genre">
                        {% for genre in genres %}
                            <option value="{{ genre.id_g }}">{{ genre.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="lengthOfSong">Length of song</label>
                    <input type="number" name="length" id="length" class="form-control">
                </div>
                <div class="form-group">
                    <label for="numberOfSongs">Number Of Plays</label>
                    <input name="number_of_plays" id="number_of_plays" type="number" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="albumSelect">Album</label>
                    <select class="form-control" name="album" id="album">
                        <option value=NULL></option>
                        {% for album in albums %}
                            <option value="{{ album.id_a }}">{{ album.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group" id="authors-container">
                    <label for="authorSelect">Authors</label>
                    <div class="input-group mb-3 author-input">
                        <select class="form-control" name="author[]" id="author">
                            <option value="">Select author</option>
                            {% for author in authors %}
                                <option value="{{ author.id_a }}">{{ author.name }}</option>
                            {% endfor %}
                        </select>
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary add-author" type="button">+</button>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="releaseYear">Release Year</label>
                    <input name="release_year" id="release_year" type="number" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="coverURL">Cover URL</label>
                    <input name="url_cover" id="url_cover" type="url" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary" style="margin-top: 10px">Add</button>
            </form>
        </div>
    </div>

    <script>
        const authorsContainer = document.querySelector('#authors-container');
        const addAuthorButton = document.querySelector('.add-author');

        addAuthorButton.addEventListener('click', () => {
            const authorInput = document.createElement('div');
            authorInput.className = 'input-group mb-3 author-input';
            authorInput.innerHTML = `
      <select class="form-control" name="author[]" id="author">
        <option value="">Select author</option>
        {% for author in authors %}
        <option value="{{ author.id_a }}">{{ author.name }}</option>
        {% endfor %}
      </select>
      <div class="input-group-append">
        <button class="btn btn-outline-secondary remove-author" type="button">-</button>
      </div>
    `;
            authorsContainer.appendChild(authorInput);
        });

        authorsContainer.addEventListener('click', (event) => {
            if (event.target.classList.contains('remove-author')) {
                event.target.closest('.author-input').remove();
            }
        });
    </script>
{% endblock %}

templates/songs/index.html
{% extends "menu.html" %}

{% block content %}
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false" data-bs-interval="false"
         style="margin-top: 20px">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            {% for i in range(songs|length) %}
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{ i + 1 }}"
                        aria-label="Slide {{ i }}"></button>
            {% endfor %}
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active text-center">
                <h5><a href="{{ url_for("songs.inspect_view", id=songs[0].id_s) }}" style="text-decoration: none; color: unset">{{ songs[0].name }}</a></h5>
                {% for author in  songs[0].authors %}
                    <p class="text-secondary" style="margin-top: 5px"><strong><a href="{{ url_for("authors.inspect_view", id=author.id_a) }}" style="text-decoration: none;color: unset">{{ author.name }}</a></strong></p>
                {% endfor %}
                {% if  songs[0].album %}
                    <p class="text-secondary">Album: <a href="{{ url_for("albums.inspect_view", id=songs[0].album.id_a) }}" style="text-decoration: none; color: unset">{{ songs[0].album.title }}</a></p>
                {% endif %}
                <img src="{{ songs[0].url_cover }}" class="d-block" alt="..."
                     style="margin-left: auto;margin-right: auto;opacity: 0.9" width="300">
                <div style="margin-top: 20px">
                    <a href="{{ url_for("songs.update_view", id=songs[0].id_s) }}" class="btn btn-light">Update</a>
                    <a href="#" class="btn btn-danger"
                       onclick="$('#songs-delete--{{ songs[0].id_s }}').submit()">Delete</a>
                    <form action="{{ url_for("songs.delete_record", id=songs[0].id_s) }}" method="POST"
                          id="song-delete--{{ songs[0].id_s }}">
                    </form>
                </div>
            </div>
            {% for song in songs[1:] %}
                <div class="carousel-item text-center">
                    <h5><a href="{{ url_for("songs.inspect_view", id=song.id_s) }}" style="text-decoration: none;color: unset">{{ song.name }}</a></h5>
                    {% for author in  song.authors %}
                        <p class="text-secondary"><strong><a href="{{ url_for("authors.inspect_view", id=author.id_a) }}" style="text-decoration: none;color: unset">{{ author.name }}</a></strong></p>
                    {% endfor %}
                    {% if  songs[0].album %}
                        <p class="text-secondary">Album: <a href="{{ url_for("albums.inspect_view", id=song.album.id_a) }}" style="text-decoration: none; color: unset">{{ song.album.title }}</a></p>
                    {% endif %}
                    {% if song.url_cover %}
                        <img src="{{ song.url_cover }}" class="d-block"
                             style="margin-left: auto;margin-right: auto;opacity: 0.8" alt="Song cover photo"
                             width="300">
                    {% elif song.album.url_cover %}
                        <img src="{{ song.album.url_cover }}" style="margin-left: auto;margin-right: auto;opacity: 0.8"
                             alt="Song cover photo" width="300">
                    {% else %}
                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1200px-No-Image-Placeholder.svg.png"
                             class="d-block w-20" width="300em" alt="No cover photo"
                             style="margin-right: auto;margin-left: auto">
                    {% endif %}
                    <div style="margin-top: 20px">
                        <a href="{{ url_for("songs.update_view", id=song.id_s) }}" class="btn btn-light">Update</a>
                        <a href="#" class="btn btn-danger"
                           onclick="$('#songs-delete--{{ song.id_s }}').submit()">Delete</a>
                        <form action="{{ url_for("songs.delete_record", id=song.id_s) }}" method="POST"
                              id="song-delete--{{ song.id_s }}">
                        </form>
                    </div>
                <!--
                TODO: When there's time, fix the overlapping buttons and slider
                -->
                </div>
            {% endfor %}
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                    data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                    data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <p class="text-left mt-3">
        <a href="{{ url_for("songs.add_view") }}" class="btn btn-primary">Add song</a>
    </p>
{% endblock %}

templates/songs/inspect.html
{% extends "menu.html" %}

{% block content %}

    <div class="card" style="width: 18rem;margin-top: 20px;margin-left: auto;margin-right: auto">
        <img src="{{ song[0].url_cover }}" class="card-img-top" alt="Photo of {{ song[0].name }}">
        <div class="card-body">
            <h5 class="card-title">{{ song[0].name }}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Release year: {{ song[0].release_year }}</li>
            <li class="list-group-item">Number of plays: {{ song[0].number_of_plays }}</li>
            <li class="list-group-item">Length in sec: {{ song[0].length }}</li>
            <li class="list-group-item">Author:
                <ul>
                    {% for author in song[0].authors %}
                    <li>{{ author.name }}</li>
                    {% endfor %}
                </ul>
            </li>
            <li class="list-group-item">Genre: {{ song[0].genre.title }}</li>
            {% if song[0].album %}
                <li class="list-group-item">Album: {{ song[0].album.title }}</li>
            {% endif %}
        </ul>
    </div>

{% endblock %}

templates/songs/update.html
{% extends "menu.html" %}

{% block content %}

    <div class="card" style="margin-top: 20px">
        <div class="card-header text-center">
            Editing <span style="font-weight: bold">{{ song.name }}</span>
        </div>
        <div class="card-body">
            <form method="post">
                <div class="form-group">
                    <label for="titleOfsong">Name of the song</label>
                    <input name="name" id="name" type="text" class="form-control" value="{{ song.name }}" required>
                </div>
                <div class="form-group">
                    <label for="authorSelect">Genre</label>
                    <select class="form-control" name="genre" id="genre">
                        <option value="{{ song.genre.id_g }}">{{ song.genre.title }}</option>
                        {% for genre in genres %}
                            {% if genre.id_g != song.genre_id %}
                                <option value="{{ genre.id_g }}">{{ genre.title }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="lengthOfSong">Length of song</label>
                    <input type="number" name="length" id="length" class="form-control" value="{{ song.length }}">
                </div>
                <div class="form-group">
                    <label for="numberOfSongs">Number Of Plays</label>
                    <input name="number_of_plays" id="number_of_plays" type="number" class="form-control"
                           value="{{ song.number_of_plays }}" required>
                </div>
                <div class="form-group">
                    <label for="albumSelect">Album</label>
                    <select class="form-control" name="album" id="album">
                        <option value="{{ song.album.id_a }}">{{ song.album.title }}</option>
                        {% for album in albums %}
                            {% if album.id_a != song.album_id %}
                                <option value="{{ album.id_a }}">{{ album.title }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="releaseYear">Release Year</label>
                    <input name="release_year" id="release_year" type="number" class="form-control"
                           value="{{ song.release_year }}" required>
                </div>
                <div class="form-group">
                    <label for="coverURL">Cover URL</label>
                    <input name="url_cover" id="url_cover" type="url" class="form-control" value="{{ song.url_cover }}">
                </div>
                <button type="submit" class="btn btn-primary" style="margin-top: 10px">Update</button>
            </form>
        </div>
    </div>

{% endblock %}